//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class HTFP14
    {
        public string COMPHT14 { get; set; }
        public string ACDEHT14 { get; set; }
        public string PGRPHT14 { get; set; }
        public string PKEYHT14 { get; set; }
        public string DESCHT14 { get; set; }
        public Nullable<decimal> PVALHT14 { get; set; }
        public string PSTRHT14 { get; set; }
        public string GLNOHT14 { get; set; }
        public string PCDEHT14 { get; set; }
        public string ATLVHT14 { get; set; }
        public string USERHT14 { get; set; }
        public System.DateTime LMDTMHT14 { get; set; }
    }
}
