// ------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本: 17.0.0.0
//  
//     对此文件的更改可能导致不正确的行为，如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CodeGenerator.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class Service : ServiceBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write(@"
using Ando.ERP.BLL.IService;
using Ando.ERP.BLL.Model;
using Ando.ERP.BLL.Model.ViewModels;
using Ando.ERP.Common.Util;
using Ando.ERP.DAL.Repository;
using Ando.ERP.DAL.Repository.IRepositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Threading.Tasks;

namespace Ando.ERP.BLL.Service
{
    /// <summary>
    /// 实现 ");
            
            #line 24 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 24 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableDesc));
            
            #line default
            #line hidden
            this.Write("表服务层接口\r\n    /// </summary>\r\n    public class ");
            
            #line 26 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write("Service : BaseService<");
            
            #line 26 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write(">, I");
            
            #line 26 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write("Service\r\n    {\r\n        private I");
            
            #line 28 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write("Reposition ");
            
            #line 28 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write("Reposition;\r\n\r\n        /// <summary>\r\n        /// Autofac 通过构造方法参数注入 I");
            
            #line 31 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write("Reposition 并实例化\r\n        /// </summary>\r\n        /// <param name=\"");
            
            #line 33 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write("Reposition\"></param>\r\n        public HTFP02Service(I");
            
            #line 34 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write("Reposition ");
            
            #line 34 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write("Reposition) : base(");
            
            #line 34 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write("Reposition)\r\n        {\r\n            this.");
            
            #line 36 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write("Reposition = ");
            
            #line 36 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write("Reposition;\r\n        }\r\n\r\n        public bool Add(");
            
            #line 39 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write("ViewModel ");
            
            #line 39 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write("ViewModel)\r\n        {\r\n            ");
            
            #line 41 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 41 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write(" = CommonUtil.TranObject2OtherType<");
            
            #line 41 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 41 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write("ViewModel);\r\n            return Add(");
            
            #line 42 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write(", false);\r\n        }\r\n\r\n        public bool Update(");
            
            #line 45 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write("ViewModel ");
            
            #line 45 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write("ViewModel)\r\n        {\r\n            ");
            
            #line 47 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 47 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write(" = CommonUtil.TranObject2OtherType<");
            
            #line 47 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 47 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write("ViewModel);\r\n            return Update(");
            
            #line 48 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write(", false);\r\n        }\r\n\r\n        public bool Delete(");
            
            #line 51 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write("ViewModel ");
            
            #line 51 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write("ViewModel)\r\n        {\r\n            ");
            
            #line 53 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 53 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write(" = CommonUtil.TranObject2OtherType<");
            
            #line 53 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write(">(");
            
            #line 53 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write("ViewModel);\r\n            return Delete(");
            
            #line 54 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TablePara));
            
            #line default
            #line hidden
            this.Write(", false);\r\n        }\r\n\r\n        public List<");
            
            #line 57 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write("ViewModel> QueryPageList(QueryPageParams queryPageParams, out int total)\r\n       " +
                    " {\r\n            /*\r\n            Expression<Func<");
            
            #line 60 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write(@", bool>> whereLambda = a => true;
            if (!string.IsNullOrEmpty(queryPageParams.SearchKeyword))
            {
                whereLambda = a => a.COMPHT02 == queryPageParams.SearchKeyword || a.MNUCDHT02 == queryPageParams.SearchKeyword; 
            }
            var list = QueryPageList(queryPageParams.PageIndex, queryPageParams.PageSize, whereLambda, (a => new { a.COMPHT02, a.MNUCDHT02 }), out total, queryPageParams.IsAsc);
            var result = CommonUtil.TranObject2OtherType<List<");
            
            #line 66 "D:\Work\study\TestProject_VS2022\CodeGenerator\Template\Service.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(model.TableName));
            
            #line default
            #line hidden
            this.Write("ViewModel>>(list);\r\n            return result;\r\n            */\r\n        }\r\n    }\r" +
                    "\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class ServiceBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
