using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.IO;
using System.Diagnostics;

namespace Console000
{
  class Class0
  {
    public static void Execute(string[] args)
    {
      //string[] s = { };
      //Console.WriteLine(s.Length);
      //=======================================

      //string s = "TMP_tcat_windows7_compatibility";
      //Console.WriteLine(s.Length);
      //s = s.Substring(0, 27) + "_" + DateTime.Now.ToString("ff");
      //Console.WriteLine(s);
      //Console.WriteLine(s.Length);
      //=======================================

      //for (var i = 0; i < 10; i++)
      //{
      //  Console.WriteLine((new Random()).Next(10, 99).ToString());
      //}
      //Console.WriteLine("**********************************************");
      //for (var i = 0; i < 10; i++)
      //{
      //  Console.WriteLine(DateTime.Now.ToString("ff"));
      //}
      //=======================================

      //DirectoryInfo dir = new DirectoryInfo(@"D:\4.3\Patch");
      //foreach (DirectoryInfo d in dir.GetDirectories("*.*"))
      //{
      //  Console.WriteLine(d.FullName);
      //}
      //=======================================

      //Console.WriteLine("start: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss ffffff"));
      //DirectoryInfo dir = new DirectoryInfo(@"D:\4.3\Patch");
      ////IEnumerable<DirectoryInfo> dirlist = dir.GetDirectories();
      //List<DirectoryInfo> dirlist = dir.GetDirectories("*").ToList();
      //Console.WriteLine(dirlist.Count());
      //IEnumerable<DirectoryInfo> derlist = dir.GetDirectories("cvs");
      //dirlist = dirlist.Except(derlist, new DirectoryInfoEquality()).ToList();
      //Console.WriteLine(dirlist.Count());
      //Console.WriteLine("end: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss ffffff"));
      //foreach (DirectoryInfo d in dirlist)
      //{
      //  Console.WriteLine(d.Name);
      //}
      //=======================================

      //Console.WriteLine("============");
      //Console.WriteLine("start: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss ffffff"));
      //DirectoryInfo dir2 = new DirectoryInfo(@"D:\4.3\Patch");
      //List<EnDirectory> dirlist2 = (from dirs in dir.GetDirectories() select new EnDirectory { FullName = dirs.FullName, Name = dirs.Name }).ToList();
      //Console.WriteLine(dirlist2.Count);
      //List<EnDirectory> derlist2 = (from dirs in dir.GetDirectories("cvs") select new EnDirectory { FullName = dirs.FullName, Name = dirs.Name }).ToList();
      //dirlist2 = dirlist2.Except(derlist2, new EnDirectoryEquality()).ToList();
      //Console.WriteLine(dirlist2.Count);
      //Console.WriteLine("end: " + DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss ffffff"));
      //foreach (EnDirectory d in dirlist)
      //{
      //  Console.WriteLine(d.FullName);
      //}
      //=======================================

      //DirectoryInfo Dir = new DirectoryInfo(@"D:\VS2013\Updateset\Patch");
      //List<string> file1 = new List<string>();
      //List<string> files = (from f in Dir.GetFiles("*.*", SearchOption.TopDirectoryOnly) select f.FullName).ToList();
      //Console.WriteLine(files.Count);
      //Console.WriteLine(file1.Count);
      //file1.AddRange(files);
      //List<string> file2 = new List<string>();
      //file1.AddRange(file2);
      //Console.WriteLine(file1.Count);
      //=======================================

      //List<string> file1 = new List<string>();
      //file1.Add("1");
      //file1.Add("2");
      //file1.Add("3");
      //Console.WriteLine(file1.Contains("1"));
      //List<string> file2 = new List<string>();
      //file2.Add("1");
      //file2.Add("2");
      //file2.Add("3");
      //Console.WriteLine(file1[0]);
      //file1 = file1.Except(file2).ToList();
      //if (file1.Count == 0) Console.WriteLine("no data");
      //foreach (string s in file1) Console.WriteLine(s);
      //=======================================

      //DirectoryInfo Dir = new DirectoryInfo(@"D:\VS2013\Updateset\Patch\US50_201510_BUG04767_ForTest");
      //FileInfo[] file1 = Dir.GetFiles("*.*", SearchOption.AllDirectories);
      //foreach (FileInfo fi in file1)
      //{
      //  Console.WriteLine(fi.FullName);
      //}
      //Console.WriteLine("=============================");
      //FileInfo[] file2 = Dir.GetFiles("AnalyzePatchSet\\*.*", SearchOption.AllDirectories);
      //foreach (FileInfo fi in file2)
      //{
      //  Console.WriteLine(fi.FullName);
      //}
      //=======================================

      //test(SearchOption.AllDirectories);
      //=======================================

      //string[] gg = System.IO.Directory.GetDirectories(@"D:\VS2013\Updateset\Pageages");
      //Console.WriteLine(gg[0]);
      //=======================================

      //DirectoryInfo dir3 = new DirectoryInfo(@"D:\VS2013\Updateset\Pageages");
      //List<DirectoryInfo> dirlist3 = dir3.GetDirectories("*").ToList();
      //dirlist3 = dirlist3.FindAll(x => x.GetFileSystemInfos().Length > 0);
      //foreach (DirectoryInfo d in dirlist3)
      //{
      //  Console.WriteLine(d.Name);
      //}
      //=======================================

      //string sPath = Environment.GetEnvironmentVariable("BMS_HOME");
      //Console.WriteLine(sPath);
      //=======================================

      //string s = string.Empty;
      //Console.WriteLine(s);
      //=======================================

      //string s = "5.0.0.1050";
      //Console.WriteLine(s.Substring(6, 4));
      //=======================================

      //string[] s = { "a" };
      //Console.WriteLine(s[0]);
      //string value = s.Length >= 2 ? s[1].Trim() : "ABC";
      //Console.WriteLine(value);
      //Console.WriteLine(s[1] ?? "b");
      //=======================================

      //string s = "a";
      //Console.WriteLine(s.PadLeft(4, ' '));
      //string ss = new string(' ', 2);
      //ss = ss + s;
      //Console.WriteLine(ss);
      //=======================================

      //Console.WriteLine("Runtime directory: {0}",  System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectory());
      //Console.WriteLine("EnvironmentVariableTarget.Machine: {0}", EnvironmentVariableTarget.Machine);
      //=======================================

      //Console.WriteLine(System.Environment.CurrentDirectory);
      //=======================================

      //List<string> l = new List<string>();
      //l.Add("02");
      //l.Add("01");
      //l.Add("05");
      //l.Add("06");
      //foreach (string s in l) Console.WriteLine(s);
      //=======================================

      //string[] l = { "Catalog", "DLLS", "For_UserConsole", "PatchSetReadme_DataPlatform", "PatchSetVersion_UserConsole", "PatchSetReadme_DataPlatform", "PatchSetVersion_DataPlatform" };
      //foreach (string s in l) Console.WriteLine(s);
      //=======================================

      //DirectoryInfo di = new DirectoryInfo(@"D:\VS2013\Updateset\Pageages");
      //Console.WriteLine(di.GetFileSystemInfos().Length);
      //=======================================

      //string Base64String = "eJy1WFlvIlcX%2fC9%2btTXcfRkpD3fFGC%2bsbTOfItRAA21Ds2NDlP%2beg%2bUZzSiR8JeAHxBGTVM6XVWn6v5xkWTLVT4rLr5esC%2f4C7q4urjN%2b1mxyuCTu5de9jJoP71OXrJ99cktnoo7T9ql1aYod2zx8LDchqI25vXJ5XLHK8lDY7%2bojGasnNy09reymAxLw8dYTMr8xqJaxaDtolcZ%2bsqseKlUitUr3y5f8HRUn3RmpaENlTw8kN3b7SttV4eT8rCT1p%2facrEdzhvXvfalu7XTzSuJHabzJNM3ixq%2fv7md7xohu9sne%2f923Sgt1ajS8Y83vT5uWUXr2D7h%2b04vu1WuIZjzSdHc2oQv0zrphPneNcu0R0tj8xyIXOTfyjbJlCgNF41VUtmWWE8rU%2b636KUej5NO77G8KZGRLDVe6smofr1utDf4gd%2fv9qHRet5PvnU6d3Jut%2bOcPPYrk6fxXTYJKiWN1mW9k78u95vGIGy02FyLb%2fVq%2feEWPVQTtdW7UaNSokmZVndPfUTmetFODX%2fmzyPaekumu2RT3cVFercc9Gezu9dv2cszv42o2YdLWrWRy0MyTvtxW6qvFvV%2bWBBbK57vh229e3StjFwm6015%2f1jlgcbVS%2b8%2b2dcbq0Vp92R6ldb9QAWUr1%2bW1ca%2bR6%2fF5vLOYp10WpXpfjzL72%2fe8kEoXTdW02nKVuOcPm3vqpWemU43k%2frwabUczbadbJ202f1OJbN5OkfrS1ydN55vp7vn8e75tdy7aZBmmc%2fDft5pJbr%2b229AMjebztNiV%2fFAs96gSIFvVxcxn2Sri6%2f%2f%2b%2bP93X06PZDQFOlkt8%2bau6L%2fZZ%2fP4bLwlvUrxSB7u%2fiKri7uBtzNBocrCQqBCeOp9EyEyBDzQhJBlA%2fUBIGNdl7xGOEWlVVznvXzdFJL1%2f3x%2b33iJB29v2lk6WSdT7MfH5SXs828tZvDb6A%2fr34Bdz9bTtNJDvA2vVV%2fmc%2fXoKUjMENAljEjFZHGS%2buMZMgaqgnmOBKGlfJMUxxOCLPdZBh3iUJId9vzQbrOPqZa2%2fQm%2bWqc5Nnr6ghsE7jhJjIVGfZYW2WjOfxZjIL11HBAjhE95XR%2fhh3zt88zwbngOKXOG%2bRICJEKr33EwlIWUVTCK9ACMe7EWMl%2fHDGxEltvpBCee40iR1pZjagzmiEcKacqOuvYWWG7dF3xbjbZTIujeDEl0RqMPDbRBiCv5wioHZTliiDPJUgSqVMzmRw4Qdn%2fyQkKsgK2WoVZQMF4B7LzAWmrHdbaRBMJEFyekhMwynQyGx0B5j2LwhEJdmC95UE5T7ENXoZouNKcOIQ54eqEwL5P7fOmZUE00jElRDSISEqDJT5IrbjQImBBTUSMGnFCkDEvRtlyvsyL9apr01V%2b7AkbbIVCRgcjpbTMAC1hgtZ4LTAjgfNgKLPylIP8GeMx2%2fdReMwQNSY64yyg1AzGCTYEYEHixrAQMT2xWGiXwFNSXTMY1JazbT7Ilu3G7RGsSPnILXUyKjAkZ4SkwfMoiZOC6yiixIpLj0%2bPVSGBu7ZWPQJQ44gVuCKhEshHPJMuRm%2bJYdpTwb2iWDOg5zkAat39iMjVbOdmm2JdKfqz5TLrr4%2bNVQM3DabgjAQHJI0DsQcPJq%2bojToa4kH8%2ftT%2bfkCNuewm%2b9rDMM0nx5iqgjY0Bk1A0d4beCcR5CZjfCQaZh4tclgxew6YinTzVXezygbdIXzvCFLsDaydSK1X3jr4z1EuJWYUXryVRB9mzMgpXek7UqJk97Auu%2f1Zse0ON0UfgK822bHZSmVZ0IoJqzxWyHJstYKawTDTEiIUcNfBejoHYkk%2bVvxHJPnYAp9JJgpagoRQ6oMXUQUuOccU4FpDsD4sfauNc%2bIMepNao4N5fUjucC1ctM6Wx7ZqxBoRwt0BtBTBo%2bC8REAQLC3UAYQp5Bbnz4L4PZr4zXyS92HcHmLAsfkyhKxH3AuCEDFIei4o9VFyuJ2Lh0oD0J08h58h1A3Fupb2X97N7JjkFNfaES2ElVJpYhQPGEOPoZRzgZyHgCqUOsMaeyfwT5Gv0%2fTZYDOHDXws%2bcEWE5HF4KHle2G4016RdxvjELixYIIyCKrngIxIt7Lu1mZdn0%2bbr9evx6A6GSDuWQdVFUOAUUpCbUEGCRkJsgL8DPkYzjFdTvmvxeXdF0LrWFYglKoAJdaZAOBh8SpHJaZGCyWghimuJHaGn9oaGEAW%2bBdC%2fJRmP9dfMHZRaS88RTY6ZTihGlnnlQxcW0iRMHeO2SkD449Ky75Pu5mtP87guj9OE46xBEirYFNIrCGJWxY9uEdEwoL2IJcrDfYGe%2fAsJwj%2fhPvjARxBLaNkFGQIaqNURoQEJYJAxTFRmMPZh6TwCOSpZfg31HCDwTT7JGiFieUHKQpjHATNgJE%2btEcMXTdSRYW0%2fpCRzlDJMaf%2fEnSQEDGFs9hQQij3BMoGMVB%2fIbRTqYIVlhArTg76ey%2f%2fd6g1w54SoLOSRmkEcR4JFFW0YNvAFxEDZA0lTs3q99gpyN9Af1aMTlkCcR6sGiPYh9oixHyI6HAyAo05CKhSRqBzWPY%2fwf7crAlV3EJCwhGc7tCXOdVEwuIBQgdIGzFErtjJtfjdtP8daMkVOfQ7CgHEYcuJdgbCUji8IuQRrEij7H9s0L9fXdymq%2fUB%2bPvhNOcE7mcns%2f5LE8hw8RUjAmENvd9oscmX2eDH9w9n1%2bgK%2f%2f7nXxQznI4%3d";
      //Stream stream   = null;
      //StreamReader sr = null;
      //try
      //{
      //  byte[] bdata    = Convert.FromBase64String(Base64String);
      //  stream          = new MemoryStream(bdata);
      //  sr              = new StreamReader(stream);
      //  string filenote = sr.ReadToEnd();
      //  Console.WriteLine(filenote);
      //}
      //finally
      //{
      //  if (stream != null) stream.Close();
      //  if (sr != null) sr.Close();
      //}
      //=======================================

      //DateTime returnFullDate = default(DateTime);
      //Console.WriteLine(returnFullDate.ToString("yyyy-MM-dd HH:mm:dd fff"));
      //=======================================

      //Console.WriteLine(Convert.ToInt16(true));
      //Console.WriteLine(Convert.ToInt16(false));
      //=======================================

      //List<string> l = new List<string>();
      //l.Add("ABC");
      //l.Add("BCD");
      //l.Add("NBIDLL");
      //l.Add("CDE");
      //l.Sort(new Comp());
      //foreach (string s in l) Console.WriteLine(s);
      //=======================================

      //相对路径
      //string s = "../../VS2013";
      //DirectoryInfo di = new DirectoryInfo(s);
      //string p = di.FullName;
      //Console.WriteLine(p);
      //=======================================

      //List<string> l1 = new List<string>();
      //l1.Add("1");
      //l1.Add("2");
      //List<string> l2 = new List<string>();
      //l2.Add("3");
      ////l2.Add("2");
      //Console.WriteLine(l1.All(l2.Contains) && l1.Count == l2.Count);
      //=======================================

      //Console.WriteLine(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
      //=======================================

      //List<int> l = new List<int>();
      //l.Add(1);
      //l.Add(3);
      //l.Add(2);
      //string s = string.Join(",", l);
      //Console.WriteLine(s);

      //l.Add("1");
      //l.Add("3");
      //l.Add("2");
      //l.Add("5");
      //string s = string.Join(",", l);
      //if (s == "") Console.WriteLine(s + "b");
      //string s = "'" + string.Join("','", l) + "'";
      //Console.WriteLine(s);
      //=======================================

      //string s = null;
      //Console.WriteLine(s + "");
      //=======================================

      //string s = "CAT_APPS_COMPATIBILITY|BIT32_COMPATIBILITY_STATUS,BIT64_COMPATIBILITY_STATUS,CAT_APPCOMP_MANUFACTURER_ID,CAT_APPCOMP_SW_EDITION_ID,CAT_APPCOMP_SW_PRODUCT_ID,CAT_APPCOMP_SW_RELEASE_ID,CAT_APPCOMP_SW_VERSION_ID,CAT_APPS_COMPATIBILITY_ID,CAT_COMPATIBILITY_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_ID,CERTIFICATION,COMMUNITY,COMPATIBILITY_STATUS,CREATE_DATE,DELETE_REASON,DESUPFLAG,DIFFICULTY,LAST_MODIFIED_DATE,OFFICIAL,REFERENCE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_COMPATIBILITY|CAT_COMPATIBILITY_DESC,CAT_COMPATIBILITY_ID,CAT_COMPATIBILITY_TYPE,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_CPE_CVE|CAT_CPE_CVE_ID,CAT_CPE_URI_ID,CAT_CVE_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_CPE_HARDWARE|CAT_CPE_HARDWARE_ID,CAT_HW_MODEL_ID,CAT_HW_MODEL_PROFILE_ID,CAT_HW_PRODUCT_ID,CAT_MANUFACTURER_ID,CPE,CREATE_DATE,DELETE_REASON,DESUPFLAG,EDITION,LAST_MODIFIED_DATE,PART,PRODUCT,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,VENDOR;CAT_CPE_SOFTWARE|CAT_CPE_SOFTWARE_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_ID,CPE,CREATE_DATE,DELETE_REASON,DESUPFLAG,EDITION,LAST_MODIFIED_DATE,PART,PRODUCT,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,VENDOR;CAT_CPE_URI|CAT_CPE_HARDWARE_ID,CAT_CPE_SOFTWARE_ID,CAT_CPE_URI_ID,CAT_HW_MODEL_ID,CAT_HW_MODEL_PROFILE_ID,CAT_HW_PRODUCT_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_TAXONOMY2012_ID,CPE_URI,CREATE_DATE,CVE_COUNT,CVSS_SCORE_MAX,CVSS_SEVERITY_MAX,DEFINITION,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,SOFTWARE_HARDWARE,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_CPU_LICENSING|CAT_CPU_LICENSING_ID,CAT_CPU_MODEL_ID,CPU_LICENSING_NOTES,CREATE_DATE,DELETE_REASON,IBMPVUPERCORE,LAST_MODIFIED_DATE,MAXSOCKETPERMC,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_CVE|CAT_CVE_ID,CREATE_DATE,CVE_PUB_DATE,CVEID,CVSS_SCORE,CVSS_SEVERITY,DELETE_REASON,LAST_MODIFIED_DATE,NVD_PUB_DATE,REPLACEMENT_ID,SUMMARY,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_DEJACODE_OPENSRC_SW|CAT_DEJACODE_OPENSRC_SW_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_TAXONOMY2012_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,NAME,OWNER,PRIMARY_UUID,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,URN,UUID,VERSION;CAT_DEJACODE_OPENSRC_SW_KWD|CAT_DEJACODE_OPENSRC_SW_ID,CAT_DEJACODE_OPENSRC_SW_KWD_ID,CREATE_DATE,DELETE_REASON,KEYWORD,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_DEJACODE_OPENSRC_SW_LIC|CAT_DEJACODE_OPENSRC_SW_ID,CAT_DEJACODE_OPENSRC_SW_LIC_ID,CREATE_DATE,DELETE_REASON,IS_PRIMARY,LAST_MODIFIED_DATE,LIC_CATEGORY,LIC_SHORT_NAME,LIC_TYPE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_FLEXERA_ARL|ARL_ID,CAT_FLEXERA_ARL_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_TAXONOMY2012_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,PRIMARY_ARL_ID,PRIMARY_CAT_SW_RELEASE_ID,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_ADDITIONAL_HW|CAT_HW_LIC_ADDITIONAL_HW_ID,CAT_HW_LIC_MODEL_ID,CAT_HW_MODEL_ID,CAT_HW_PRODUCT_ID,CAT_MANUFACTURER_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_ADDITIONAL_SW|CAT_HW_LIC_ADDITIONAL_SW_ID,CAT_HW_LIC_MODEL_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,REQ_SPECIFIC_VERSION,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_CHARACTERISTICS|CAT_HW_LIC_CHARACTERISTICS_ID,CREATE_DATE,DATA_LINK_PROTOCOL,DELETE_REASON,GRAPHICS_CARD,HARDDRIVE_INTERFACE,INSTALLED_RAM,INSTALLED_RAM_UNIT,INTERFACE_PORTS,LAST_MODIFIED_DATE,MEMORY_MAX,MEMORY_MAX_UNIT,MEMORY_SPECIFICATION,MEMORY_SPEED,MEMORY_STORAGE_CAPACITY,MEMORY_STORAGE_UNIT,MEMORY_TECHNOLOGY,MONITOR_RESOLUTION_LENGTH,MONITOR_RESOLUTION_WIDTH,NETWORK_TYPE,OPTICAL_DRIVE,PROCESSOR_INSTALLED_QTY,PROCESSOR_MAX_SUPPORTED,PROCESSOR_SPEED,PROCESSOR_TYPE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_CPU|CAT_CPU_MODEL_ID,CAT_HW_LIC_CPU_ID,CAT_HW_LIC_MODEL_ID,CAT_MANUFACTURER_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_MFRPARTNO_LPRICE|ACTUAL_PRICE,CAT_CURRENCY_ID,CAT_HW_LIC_MFRPARTNO_LPRICE_ID,CAT_HW_LIC_MODEL_ID,CREATE_DATE,DEFAULT_CURRENCY,DELETE_REASON,LAST_MODIFIED_DATE,LIST_PRICE,MFRPARTNO,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_MODEL|CAT_HW_LIC_CHARACTERISTICS_ID,CAT_HW_LIC_TYPE_ID,CAT_HW_LIC_UPS_ID,CAT_HW_MODEL_PROFILE_ID,LICENSE_TYPE,MAINT_PERIOD_UNIT,MAINT_PERIOD_VALUE,MAINT_PEROID_UNIT,MAINT_PEROID_VALUE,METRICS,PERIOD_UNIT,PERIOD_VALUE,TERM,TERM_OTHER,UNIT_COUNT_MAX,UNIT_COUNT_MIN,UNIT_PACK,VENDOR_PRODUCT_NAME,VENDOR_UNIT_OF_MEASURE;CAT_HW_LIC_PRODUCT|CAT_HW_MODEL_PROFILE_ID,LIC_MANUFACTURER,LIC_PRODUCT;CAT_HW_LIC_TYPE|CAT_HW_LIC_TYPE_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,LICENSE_TYPE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_UPS|CAT_HW_LIC_UPS_ID,CREATE_DATE,DELETE_REASON,INPUT_FREQUENCY,INPUT_VOLTAGE,INPUT_VOLTAGE_RANGE,INPUT_VOLTAGE_UNIT,LAST_MODIFIED_DATE,OUTLETS,OUTPUT_VOLTAGE,OUTPUT_VOLTAGE_UNIT,POWER_PROVIDED,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIFECYCLE|CAT_HW_LIFECYCLE_ID,CAT_HW_MODEL_ID,CREATE_DATE,DELETE_REASON,GA_EXCEPTION,GA_RANGE_END,GA_RANGE_START,GENERAL_AVAILABILITY,GENERAL_AVAILABILITY_STR,INRODUCTION_EXCEPTION,INTRODUCTION,INTRODUCTION_RANGE_END,INTRODUCTION_RANGE_START,INTRODUCTION_STR,LAST_AVAIL_RANGE_END,LAST_AVAIL_RANGE_START,LAST_AVAILABILITY,LAST_AVAILABILITY_EXCEPTION,LAST_AVAILABILITY_STR,LAST_MODIFIED_DATE,OBSOLETE,OBSOLETE_EXCEPTION,OBSOLETE_RANGE_END,OBSOLETE_RANGE_START,OBSOLETE_STR,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_MODEL|AC_AVG_UNIT,AC_FREQ_MAX,AC_FREQ_MIN,AC_HEAT_DISS_AVG,AC_HEAT_DISS_MAX,AC_INPUT_HIGH_CURRENT_MAX,AC_INPUT_HIGH_CURRENT_MIN,AC_INPUT_HIGH_VOLT_MAX,AC_INPUT_HIGH_VOLT_MIN,AC_INPUT_LOW_CURRENT_MAX,AC_INPUT_LOW_CURRENT_MIN,AC_INPUT_LOW_VOLT_MAX,AC_INPUT_LOW_VOLT_MIN,AC_MAX_UNIT,AC_POWER_AVG,AC_POWER_MAX,DATE_AVAILABLE,DATE_INTRODUCED,DC_HEAT_DISS_AVG,DC_HEAT_DISS_MAX,DC_HIGH_CURRENT,DC_HIGH_VOLT,DC_LOW_CURRENT,DC_LOW_VOLT,DC_POWER_AVG,DC_POWER_MAX,END_OF_LIFE_DATE,END_OF_SALES_DATE,ENERGY_STAR,EPEAT,LAST_SHIP_DATE,LAST_SUPPORT_DATE,MAX_NON_OPERATING_HUMIDITY,MAX_NON_OPERATING_TEMP,MAX_OPERATING_HUMIDITY,MAX_OPERATING_TEMP,MIN_NON_OPERATING_HUMIDITY,MIN_NON_OPERATING_TEMP,MIN_OPERATING_HUMIDITY,MIN_OPERATING_TEMP,POWER_RATING;CAT_HW_MODEL_POWER|AC_AVG_UNIT,AC_FREQ_MAX,AC_FREQ_MIN,AC_HEAT_DISS_AVG,AC_HEAT_DISS_MAX,AC_INPUT_HIGH_CURRENT_MAX,AC_INPUT_HIGH_CURRENT_MIN,AC_INPUT_HIGH_VOLT_MAX,AC_INPUT_HIGH_VOLT_MIN,AC_INPUT_LOW_CURRENT_MAX,AC_INPUT_LOW_CURRENT_MIN,AC_INPUT_LOW_VOLT_MAX,AC_INPUT_LOW_VOLT_MIN,AC_MAX_UNIT,AC_POWER_AVG,AC_POWER_MAX,CAT_HW_MODEL_ID,CAT_HW_MODEL_POWER_ID,CREATE_DATE,DC_HEAT_DISS_AVG,DC_HEAT_DISS_MAX,DC_HIGH_CURRENT,DC_HIGH_VOLT,DC_LOW_CURRENT,DC_LOW_VOLT,DC_POWER_AVG,DC_POWER_MAX,DELETE_REASON,ENERGY_STAR,EPEAT,LAST_MODIFIED_DATE,MAX_NON_OPERATING_HUMIDITY,MAX_NON_OPERATING_TEMP,MAX_OPERATING_HUMIDITY,MAX_OPERATING_TEMP,MIN_NON_OPERATING_HUMIDITY,MIN_NON_OPERATING_TEMP,MIN_OPERATING_HUMIDITY,MIN_OPERATING_TEMP,POWER_RATING,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_MODEL_PROFILE|CAT_HW_MODEL_ID,CAT_HW_MODEL_PROFILE_ID,CAT_HW_PRODUCT_ID,CAT_MANUFACTURER_ID,CAT_TAXONOMY_ID,CAT_TAXONOMY2012_ID,CREATE_DATE,DELETE_REASON,DESUPFLAG,HW_MODEL_ID,HW_PRODUCT_ID,ID,LAST_MODIFIED_DATE,MANUFACTURER_ID,MAX_DEPTH,MAX_HEIGHT,MAX_WEIGHT,MAX_WIDTH,MIN_DEPTH,MIN_HEIGHT,MIN_WEIGHT,MIN_WIDTH,MODEL_PROFILE,PROFILE,REPLACEMENT_ID,TAXONOMY_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_PRICING|AVG_PRICE,CAT_CURRENCY_ID,CAT_HW_MODEL_ID,CAT_HW_MODEL_PROFILE_ID,CAT_HW_PRICING_ID,CAT_HW_PRODUCT_ID,CAT_MANUFACTURER_ID,CAT_TAXONOMY2012_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,MAX_PRICE,MIN_PRICE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_MFRPARTNO|ACTUAL_PRICE,CAT_HW_MODEL_ID,CAT_HW_MODEL_PROFILE_ID,CAT_HW_PRODUCT_ID,CAT_MANUFACTURER_ID,CAT_MFRPARTNO_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_TAXONOMY_TYPE,CAT_TAXONOMY2012_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,LIST_PRICE,MFR_PART_NO,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_OS_SYSTEM_REQUIREMENTS|BIT_MODE,CAT_MANUFACTURER_ID,CAT_OS_SYSTEM_REQUIREMENTS_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CPU_SPEED,CREATE_DATE,DELETE_REASON,GRAPHICS_CARD,GRAPHICS_CARD_DRIVER,HDD_FREE_SPACE,LAST_MODIFIED_DATE,MONITOR_LEN,MONITOR_WID,NOTES,OPTICAL_DRIVE,OS_TYPE,OTHER_REQ_TYPE,OTHER_SOURCE,PHYSICAL_RAM_LIMIT,RAM,REFERENCE,REPLACEMENT_ID,REQ_SOURCE,REQ_TYPE,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SUPPORT_POLICY|CAT_MANUFACTURER_ID,CAT_SUPPORT_POLICY_ID,CREATE_DATE,DELETE_REASON,ID,LABEL,LAST_MODIFIED_DATE,MANUFACTURER_ID,REPLACEMENT_ID,SUPPORT_POLICY,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SUPPORT_STAGE|CAT_SUPPORT_POLICY_ID,CAT_SUPPORT_STAGE_ID,CREATE_DATE,DELETE_REASON,ID,LABEL,LAST_MODIFIED_DATE,REPLACEMENT_ID,STAGEORDER,SUPP_STAGE_DEF,SUPPORT_POLICY_ID,SUPPORT_STAGE,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_ADDITIONAL_SW|CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_LIC_ADDITIONAL_SW_ID,CAT_SW_LIC_RELEASE_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,REQ_SPECIFIC_VERSION,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_DIST_MEDIA|CAT_SW_LIC_DIST_MEDIA_ID,CREATE_DATE,DELETE_REASON,DISTRIBUTION_MEDIA,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_DIST_MEDIAS|CAT_SW_LIC_DIST_MEDIA_ID,CAT_SW_LIC_DIST_MEDIAS_ID,CREATE_DATE,DELETE_REASON,DISTRIBUTION_MEDIAS_ID,LAST_MODIFIED_DATE,ORD,QUANTITY,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_ENVIRONMENT|CAT_SW_LIC_ENVIRONMENT_ID,CREATE_DATE,DELETE_REASON,ENVIRONMENT,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_ENVIRONMENTS|CAT_SW_LIC_ENVIRONMENT_ID,CAT_SW_LIC_ENVIRONMENTS_ID,CREATE_DATE,DELETE_REASON,ENVIRONMENTS_ID,LAST_MODIFIED_DATE,ORD,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_LANGUAGE|CAT_SW_LIC_LANGUAGE_ID,CREATE_DATE,DELETE_REASON,LANGUAGE,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_LANGUAGES|CAT_SW_LIC_LANGUAGE_ID,CAT_SW_LIC_LANGUAGES_ID,CREATE_DATE,DELETE_REASON,LANGUAGES_ID,LAST_MODIFIED_DATE,ORD,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_MAINT_GRADE|CAT_MANUFACTURER_ID,CAT_SW_LIC_MAINT_GRADE_ID,CREATE_DATE,DEFINITION,DELETE_REASON,LAST_MODIFIED_DATE,MAINTENANCE_GRADE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,URL;CAT_SW_LIC_MAINT_GRADES|CAT_SW_LIC_MAINT_GRADE_ID,CAT_SW_LIC_MAINT_GRADES_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,MAINTENANCE_GRADES_ID,ORD,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_METRIC|CAT_SW_LIC_METRIC_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,LICENSE_METRIC1,LICENSE_METRIC2,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_METRICS|CAT_SW_LIC_METRIC_ID,CAT_SW_LIC_METRICS_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,LICENSE_METRICS_ID,MAX_VAL,MIN_VAL,ORD,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_MFRPARTNO_LPRICE|ACTUAL_PRICE,CAT_CURRENCY_ID,CAT_SW_LIC_MFRPARTNO_LPRICE_ID,CAT_SW_LIC_RELEASE_ID,CREATE_DATE,DEFAULT_CURRENCY,DELETE_REASON,LAST_MODIFIED_DATE,LIST_PRICE,MFRPARTNO,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_PRICE_LEVEL|CAT_MANUFACTURER_ID,CAT_SW_LIC_PRICE_LEVEL_ID,CREATE_DATE,DEFINITION,DELETE_REASON,LAST_MODIFIED_DATE,PRICE_LEVEL,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,URL;CAT_SW_LIC_PRICE_LEVELS|CAT_SW_LIC_PRICE_LEVEL_ID,CAT_SW_LIC_PRICE_LEVELS_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,ORD,PRICE_LEVELS_ID,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_PRICING|CAT_MANUFACTURER_ID,CAT_SW_LIC_PRICING_ID,CREATE_DATE,DEFINITION,DELETE_REASON,LAST_MODIFIED_DATE,PRICING,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,URL;CAT_SW_LIC_PRICINGS|CAT_SW_LIC_PRICING_ID,CAT_SW_LIC_PRICINGS_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,ORD,PRICINGS_ID,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_PRODUCT|LIC_MANUFACTURER,LIC_PRODUCT,REQ_SPECIFIC_VERSION;CAT_SW_LIC_PROGRAM|CAT_MANUFACTURER_ID,CAT_SW_LIC_PROGRAM_ID,CREATE_DATE,DEFINITION,DELETE_REASON,LAST_MODIFIED_DATE,PROGRAM,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,URL;CAT_SW_LIC_PROGRAMS|CAT_SW_LIC_PROGRAM_ID,CAT_SW_LIC_PROGRAMS_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,ORD,PROGRAMS_ID,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_RELEASE|CORE_FACTOR,CROSS_LANGUAGE_AUTH,CROSS_PLATFORMS_AUTH,DISTRIBUTION_MEDIAS,DISTRIBUTION_MEDIAS_ID,DOWNGRADE_DATE_MONTHS_MAX,DOWNGRADE_DATE_MONTHS_MIN,DOWNGRADE_EDITION_AUTH,DOWNGRADE_EDITION_INCR,DOWNGRADE_VERSION_AUTH,DOWNGRADE_VERSION_INCR,DUAL_LICENSE_AUTH,ENVIRONMENTS,ENVIRONMENTS_ID,ENVIRONMENTS_OTHER,LANGUAGES,LANGUAGES_ID,LICENSE_INFORMATION_OTHER,LICENSE_METRICS,LICENSE_METRICS_ID,LICENSE_TERM,LICENSE_TYPES,LICENSE_TYPES_ID,LICENSE_TYPES_OTHER,MAINT_PERIOD_UNIT,MAINT_PERIOD_VALUE,MAINT_PEROID_UNIT,MAINT_PEROID_VALUE,MAINTENANCE_GRADES,MAINTENANCE_GRADES_ID,PERIOD_UNIT,PERIOD_VALUE,PRICE_LEVELS,PRICE_LEVELS_ID,PRICINGS,PRICINGS_ID,PROGRAMS,PROGRAMS_ID,REASSIGNMENT_AUTH,REQ_SPECIFIC_VERSION,UNIT_COUNT_MAX,UNIT_COUNT_MIN,UNIT_PACK,UPGRADE_DATE_MONTHS_MAX,UPGRADE_DATE_MONTHS_MIN,UPGRADE_EDITION_AUTH,UPGRADE_EDITION_INCR,UPGRADE_VERSION_AUTH,UPGRADE_VERSION_INCR,VENDOR_PRODUCT_NAME,VENDOR_UNIT_OF_MEASURE,VIRTUAL_INSTALL_AUTH,VIRTUAL_INSTALL_MAX;CAT_SW_LIC_TYPE|CAT_SW_LIC_TYPE_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,LICENSE_TYPE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_TYPES|CAT_SW_LIC_TYPE_ID,CAT_SW_LIC_TYPES_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,LICENSE_TYPES_ID,ORD,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_UPGRADE_FROM|CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_LIC_RELEASE_ID,CAT_SW_LIC_UPGRADE_FROM_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,REQ_SPECIFIC_VERSION,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_PRICING|AVG_PRICE,CAT_CURRENCY_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRICING_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_TAXONOMY2012_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,MAX_PRICE,MIN_PRICE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_REL_LIFECYCLE|CAT_SW_REL_LIFECYCLE_ID,CAT_SW_RELEASE_ID,CREATE_DATE,DELETE_REASON,END_OF_LIFE,END_OF_LIFE_EXCEPTION,END_OF_LIFE_RANGE_END,END_OF_LIFE_RANGE_START,END_OF_LIFE_STR,END_OF_LIFE_SUPPORT_LEVEL,GA_EXCEPTION,GA_RANGE_END,GA_RANGE_START,GENERAL_AVAILABILITY,GENERAL_AVAILABILITY_STR,LAST_MODIFIED_DATE,OBSOLETE,OBSOLETE_EXCEPTION,OBSOLETE_RANGE_END,OBSOLETE_RANGE_START,OBSOLETE_STR,OBSOLETE_SUPPORT_LEVEL,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_REL_SUPP_STAGE|CAT_SUPPORT_STAGE_ID,CAT_SW_REL_SUPP_STAGE_ID,CAT_SW_RELEASE_ID,CREATE_DATE,DATE_ENDDATE,DELETE_REASON,ID,LAST_MODIFIED_DATE,PUBLISHED_ENDDATE,REL_SUPP_STAGE,RELEASE_ID,REPLACEMENT_ID,STAGE_NAME,STAGEORDER,SUPPORT_STAGE_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_WINDOWS7_COMPATIBILITY|CAT_COMPATIBILITY_ID,CAT_COMPATIBILITY_TYPE,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_WINDOWS7_COMPATIBILITY_ID,COMPONENT,CREATE_DATE,DELETE_REASON,EDITION,FAMILY,LAST_MODIFIED_DATE,MANUFACTURER,PATCHLEVEL,REPLACEMENT_ID,SOFTWARE,SUBVERSION,TO_BE_DELETED,TO_BE_DELETED_ON,VERSION,VERSION_GROUP,WIN7_32BIT_COMPAT_DATE,WIN7_32BIT_COMPAT_STATUS,WIN7_32BIT_COMPAT_STATUS_DESC,WIN7_32BIT_COMPAT_UPGRADE_PATH,WIN7_64BIT_COMPAT_DATE,WIN7_64BIT_COMPAT_STATUS,WIN7_64BIT_COMPAT_STATUS_DESC,WIN7_64BIT_COMPAT_UPGRADE_PATH;CAT_WINDOWS8_COMPATIBILITY|CAT_COMPATIBILITY_ID,CAT_COMPATIBILITY_TYPE,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_WINDOWS8_COMPATIBILITY_ID,COMMUNITY_COMPATIBLE,COMMUNITY_NOT_COMPATIBLE,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,WIN8_32BIT_COMPAT_DATE,WIN8_32BIT_COMPAT_STATUS,WIN8_32BIT_COMPAT_STATUS_DESC,WIN8_32BIT_COMPAT_UPGRADE_PATH,WIN8_64BIT_COMPAT_DATE,WIN8_64BIT_COMPAT_STATUS,WIN8_64BIT_COMPAT_STATUS_DESC,WIN8_64BIT_COMPAT_UPGRADE_PATH;CAT_WINSERVER_COMPATIBILITY|BIT32_COMPAT_STATUS,BIT32_COMPAT_STATUS_DESC,BIT64_COMPAT_STATUS,BIT64_COMPAT_STATUS_DESC,CAT_COMPATIBILITY_ID,CAT_COMPATIBILITY_TYPE,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_WINSERVER_COMPATIBILITY_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REFERENCE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON";
      //string b = "CAT_APPS_COMPATIBILITY|BIT32_COMPATIBILITY_STATUS,BIT64_COMPATIBILITY_STATUS,CAT_APPCOMP_MANUFACTURER_ID,CAT_APPCOMP_SW_EDITION_ID,CAT_APPCOMP_SW_PRODUCT_ID,CAT_APPCOMP_SW_RELEASE_ID,CAT_APPCOMP_SW_VERSION_ID,CAT_APPS_COMPATIBILITY_ID,CAT_COMPATIBILITY_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_ID,CERTIFICATION,COMMUNITY,COMPATIBILITY_STATUS,CREATE_DATE,DELETE_REASON,DESUPFLAG,DIFFICULTY,LAST_MODIFIED_DATE,OFFICIAL,REFERENCE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_COMPATIBILITY|CAT_COMPATIBILITY_DESC,CAT_COMPATIBILITY_ID,CAT_COMPATIBILITY_TYPE,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_CPE_CVE|CAT_CPE_CVE_ID,CAT_CPE_URI_ID,CAT_CVE_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_CPE_HARDWARE|CAT_CPE_HARDWARE_ID,CAT_HW_MODEL_ID,CAT_HW_MODEL_PROFILE_ID,CAT_HW_PRODUCT_ID,CAT_MANUFACTURER_ID,CPE,CREATE_DATE,DELETE_REASON,DESUPFLAG,EDITION,LAST_MODIFIED_DATE,PART,PRODUCT,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,VENDOR;CAT_CPE_SOFTWARE|CAT_CPE_SOFTWARE_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_ID,CPE,CREATE_DATE,DELETE_REASON,DESUPFLAG,EDITION,LAST_MODIFIED_DATE,PART,PRODUCT,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,VENDOR;CAT_CPE_URI|CAT_CPE_HARDWARE_ID,CAT_CPE_SOFTWARE_ID,CAT_CPE_URI_ID,CAT_HW_MODEL_ID,CAT_HW_MODEL_PROFILE_ID,CAT_HW_PRODUCT_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_TAXONOMY2012_ID,CPE_URI,CREATE_DATE,CVE_COUNT,CVSS_SCORE_MAX,CVSS_SEVERITY_MAX,DEFINITION,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,SOFTWARE_HARDWARE,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_CPU_LICENSING|CAT_CPU_LICENSING_ID,CAT_CPU_MODEL_ID,CPU_LICENSING_NOTES,CREATE_DATE,DELETE_REASON,IBMPVUPERCORE,LAST_MODIFIED_DATE,MAXSOCKETPERMC,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_CVE|CAT_CVE_ID,CREATE_DATE,CVE_PUB_DATE,CVEID,CVSS_SCORE,CVSS_SEVERITY,DELETE_REASON,LAST_MODIFIED_DATE,NVD_PUB_DATE,REPLACEMENT_ID,SUMMARY,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_DEJACODE_OPENSRC_SW|CAT_DEJACODE_OPENSRC_SW_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_TAXONOMY2012_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,NAME,OWNER,PRIMARY_UUID,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,URN,UUID,VERSION;CAT_DEJACODE_OPENSRC_SW_KWD|CAT_DEJACODE_OPENSRC_SW_ID,CAT_DEJACODE_OPENSRC_SW_KWD_ID,CREATE_DATE,DELETE_REASON,KEYWORD,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_DEJACODE_OPENSRC_SW_LIC|CAT_DEJACODE_OPENSRC_SW_ID,CAT_DEJACODE_OPENSRC_SW_LIC_ID,CREATE_DATE,DELETE_REASON,IS_PRIMARY,LAST_MODIFIED_DATE,LIC_CATEGORY,LIC_SHORT_NAME,LIC_TYPE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_FLEXERA_ARL|ARL_ID,CAT_FLEXERA_ARL_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_TAXONOMY2012_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,PRIMARY_ARL_ID,PRIMARY_CAT_SW_RELEASE_ID,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_ADDITIONAL_HW|CAT_HW_LIC_ADDITIONAL_HW_ID,CAT_HW_LIC_MODEL_ID,CAT_HW_MODEL_ID,CAT_HW_PRODUCT_ID,CAT_MANUFACTURER_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_ADDITIONAL_SW|CAT_HW_LIC_ADDITIONAL_SW_ID,CAT_HW_LIC_MODEL_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,REQ_SPECIFIC_VERSION,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_CHARACTERISTICS|CAT_HW_LIC_CHARACTERISTICS_ID,CREATE_DATE,DATA_LINK_PROTOCOL,DELETE_REASON,GRAPHICS_CARD,HARDDRIVE_INTERFACE,INSTALLED_RAM,INSTALLED_RAM_UNIT,INTERFACE_PORTS,LAST_MODIFIED_DATE,MEMORY_MAX,MEMORY_MAX_UNIT,MEMORY_SPECIFICATION,MEMORY_SPEED,MEMORY_STORAGE_CAPACITY,MEMORY_STORAGE_UNIT,MEMORY_TECHNOLOGY,MONITOR_RESOLUTION_LENGTH,MONITOR_RESOLUTION_WIDTH,NETWORK_TYPE,OPTICAL_DRIVE,PROCESSOR_INSTALLED_QTY,PROCESSOR_MAX_SUPPORTED,PROCESSOR_SPEED,PROCESSOR_TYPE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_CPU|CAT_CPU_MODEL_ID,CAT_HW_LIC_CPU_ID,CAT_HW_LIC_MODEL_ID,CAT_MANUFACTURER_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_MFRPARTNO_LPRICE|ACTUAL_PRICE,CAT_CURRENCY_ID,CAT_HW_LIC_MFRPARTNO_LPRICE_ID,CAT_HW_LIC_MODEL_ID,CREATE_DATE,DEFAULT_CURRENCY,DELETE_REASON,LAST_MODIFIED_DATE,LIST_PRICE,MFRPARTNO,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_TYPE|CAT_HW_LIC_TYPE_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,LICENSE_TYPE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIC_UPS|CAT_HW_LIC_UPS_ID,CREATE_DATE,DELETE_REASON,INPUT_FREQUENCY,INPUT_VOLTAGE,INPUT_VOLTAGE_RANGE,INPUT_VOLTAGE_UNIT,LAST_MODIFIED_DATE,OUTLETS,OUTPUT_VOLTAGE,OUTPUT_VOLTAGE_UNIT,POWER_PROVIDED,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_LIFECYCLE|CAT_HW_LIFECYCLE_ID,CAT_HW_MODEL_ID,CREATE_DATE,DELETE_REASON,GA_EXCEPTION,GA_RANGE_END,GA_RANGE_START,GENERAL_AVAILABILITY,GENERAL_AVAILABILITY_STR,INRODUCTION_EXCEPTION,INTRODUCTION,INTRODUCTION_RANGE_END,INTRODUCTION_RANGE_START,INTRODUCTION_STR,LAST_AVAIL_RANGE_END,LAST_AVAIL_RANGE_START,LAST_AVAILABILITY,LAST_AVAILABILITY_EXCEPTION,LAST_AVAILABILITY_STR,LAST_MODIFIED_DATE,OBSOLETE,OBSOLETE_EXCEPTION,OBSOLETE_RANGE_END,OBSOLETE_RANGE_START,OBSOLETE_STR,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_MODEL_POWER|AC_AVG_UNIT,AC_FREQ_MAX,AC_FREQ_MIN,AC_HEAT_DISS_AVG,AC_HEAT_DISS_MAX,AC_INPUT_HIGH_CURRENT_MAX,AC_INPUT_HIGH_CURRENT_MIN,AC_INPUT_HIGH_VOLT_MAX,AC_INPUT_HIGH_VOLT_MIN,AC_INPUT_LOW_CURRENT_MAX,AC_INPUT_LOW_CURRENT_MIN,AC_INPUT_LOW_VOLT_MAX,AC_INPUT_LOW_VOLT_MIN,AC_MAX_UNIT,AC_POWER_AVG,AC_POWER_MAX,CAT_HW_MODEL_ID,CAT_HW_MODEL_POWER_ID,CREATE_DATE,DC_HEAT_DISS_AVG,DC_HEAT_DISS_MAX,DC_HIGH_CURRENT,DC_HIGH_VOLT,DC_LOW_CURRENT,DC_LOW_VOLT,DC_POWER_AVG,DC_POWER_MAX,DELETE_REASON,ENERGY_STAR,EPEAT,LAST_MODIFIED_DATE,MAX_NON_OPERATING_HUMIDITY,MAX_NON_OPERATING_TEMP,MAX_OPERATING_HUMIDITY,MAX_OPERATING_TEMP,MIN_NON_OPERATING_HUMIDITY,MIN_NON_OPERATING_TEMP,MIN_OPERATING_HUMIDITY,MIN_OPERATING_TEMP,POWER_RATING,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_MODEL_PROFILE|CAT_HW_MODEL_ID,CAT_HW_MODEL_PROFILE_ID,CAT_HW_PRODUCT_ID,CAT_MANUFACTURER_ID,CAT_TAXONOMY_ID,CAT_TAXONOMY2012_ID,CREATE_DATE,DELETE_REASON,DESUPFLAG,HW_MODEL_ID,HW_PRODUCT_ID,ID,LAST_MODIFIED_DATE,MANUFACTURER_ID,MAX_DEPTH,MAX_HEIGHT,MAX_WEIGHT,MAX_WIDTH,MIN_DEPTH,MIN_HEIGHT,MIN_WEIGHT,MIN_WIDTH,MODEL_PROFILE,PROFILE,REPLACEMENT_ID,TAXONOMY_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_HW_PRICING|AVG_PRICE,CAT_CURRENCY_ID,CAT_HW_MODEL_ID,CAT_HW_MODEL_PROFILE_ID,CAT_HW_PRICING_ID,CAT_HW_PRODUCT_ID,CAT_MANUFACTURER_ID,CAT_TAXONOMY2012_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,MAX_PRICE,MIN_PRICE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_MFRPARTNO|ACTUAL_PRICE,CAT_HW_MODEL_ID,CAT_HW_MODEL_PROFILE_ID,CAT_HW_PRODUCT_ID,CAT_MANUFACTURER_ID,CAT_MFRPARTNO_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_TAXONOMY_TYPE,CAT_TAXONOMY2012_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,LIST_PRICE,MFR_PART_NO,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_OS_SYSTEM_REQUIREMENTS|BIT_MODE,CAT_MANUFACTURER_ID,CAT_OS_SYSTEM_REQUIREMENTS_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CPU_SPEED,CREATE_DATE,DELETE_REASON,GRAPHICS_CARD,GRAPHICS_CARD_DRIVER,HDD_FREE_SPACE,LAST_MODIFIED_DATE,MONITOR_LEN,MONITOR_WID,NOTES,OPTICAL_DRIVE,OS_TYPE,OTHER_REQ_TYPE,OTHER_SOURCE,PHYSICAL_RAM_LIMIT,RAM,REFERENCE,REPLACEMENT_ID,REQ_SOURCE,REQ_TYPE,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SUPPORT_POLICY|CAT_MANUFACTURER_ID,CAT_SUPPORT_POLICY_ID,CREATE_DATE,DELETE_REASON,ID,LABEL,LAST_MODIFIED_DATE,MANUFACTURER_ID,REPLACEMENT_ID,SUPPORT_POLICY,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SUPPORT_STAGE|CAT_SUPPORT_POLICY_ID,CAT_SUPPORT_STAGE_ID,CREATE_DATE,DELETE_REASON,ID,LABEL,LAST_MODIFIED_DATE,REPLACEMENT_ID,STAGEORDER,SUPP_STAGE_DEF,SUPPORT_POLICY_ID,SUPPORT_STAGE,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_ADDITIONAL_SW|CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_LIC_ADDITIONAL_SW_ID,CAT_SW_LIC_RELEASE_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,REQ_SPECIFIC_VERSION,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_DIST_MEDIA|CAT_SW_LIC_DIST_MEDIA_ID,CREATE_DATE,DELETE_REASON,DISTRIBUTION_MEDIA,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_DIST_MEDIAS|CAT_SW_LIC_DIST_MEDIA_ID,CAT_SW_LIC_DIST_MEDIAS_ID,CREATE_DATE,DELETE_REASON,DISTRIBUTION_MEDIAS_ID,LAST_MODIFIED_DATE,ORD,QUANTITY,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_ENVIRONMENT|CAT_SW_LIC_ENVIRONMENT_ID,CREATE_DATE,DELETE_REASON,ENVIRONMENT,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_ENVIRONMENTS|CAT_SW_LIC_ENVIRONMENT_ID,CAT_SW_LIC_ENVIRONMENTS_ID,CREATE_DATE,DELETE_REASON,ENVIRONMENTS_ID,LAST_MODIFIED_DATE,ORD,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_LANGUAGE|CAT_SW_LIC_LANGUAGE_ID,CREATE_DATE,DELETE_REASON,LANGUAGE,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_LANGUAGES|CAT_SW_LIC_LANGUAGE_ID,CAT_SW_LIC_LANGUAGES_ID,CREATE_DATE,DELETE_REASON,LANGUAGES_ID,LAST_MODIFIED_DATE,ORD,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_MAINT_GRADE|CAT_MANUFACTURER_ID,CAT_SW_LIC_MAINT_GRADE_ID,CREATE_DATE,DEFINITION,DELETE_REASON,LAST_MODIFIED_DATE,MAINTENANCE_GRADE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,URL;CAT_SW_LIC_MAINT_GRADES|CAT_SW_LIC_MAINT_GRADE_ID,CAT_SW_LIC_MAINT_GRADES_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,MAINTENANCE_GRADES_ID,ORD,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_METRIC|CAT_SW_LIC_METRIC_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,LICENSE_METRIC1,LICENSE_METRIC2,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_METRICS|CAT_SW_LIC_METRIC_ID,CAT_SW_LIC_METRICS_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,LICENSE_METRICS_ID,MAX_VAL,MIN_VAL,ORD,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_MFRPARTNO_LPRICE|ACTUAL_PRICE,CAT_CURRENCY_ID,CAT_SW_LIC_MFRPARTNO_LPRICE_ID,CAT_SW_LIC_RELEASE_ID,CREATE_DATE,DEFAULT_CURRENCY,DELETE_REASON,LAST_MODIFIED_DATE,LIST_PRICE,MFRPARTNO,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_PRICE_LEVEL|CAT_MANUFACTURER_ID,CAT_SW_LIC_PRICE_LEVEL_ID,CREATE_DATE,DEFINITION,DELETE_REASON,LAST_MODIFIED_DATE,PRICE_LEVEL,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,URL;CAT_SW_LIC_PRICE_LEVELS|CAT_SW_LIC_PRICE_LEVEL_ID,CAT_SW_LIC_PRICE_LEVELS_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,ORD,PRICE_LEVELS_ID,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_PRICING|CAT_MANUFACTURER_ID,CAT_SW_LIC_PRICING_ID,CREATE_DATE,DEFINITION,DELETE_REASON,LAST_MODIFIED_DATE,PRICING,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,URL;CAT_SW_LIC_PRICINGS|CAT_SW_LIC_PRICING_ID,CAT_SW_LIC_PRICINGS_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,ORD,PRICINGS_ID,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_PROGRAM|CAT_MANUFACTURER_ID,CAT_SW_LIC_PROGRAM_ID,CREATE_DATE,DEFINITION,DELETE_REASON,LAST_MODIFIED_DATE,PROGRAM,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,URL;CAT_SW_LIC_PROGRAMS|CAT_SW_LIC_PROGRAM_ID,CAT_SW_LIC_PROGRAMS_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,ORD,PROGRAMS_ID,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_TYPE|CAT_SW_LIC_TYPE_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,LICENSE_TYPE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_TYPES|CAT_SW_LIC_TYPE_ID,CAT_SW_LIC_TYPES_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,LICENSE_TYPES_ID,ORD,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_LIC_UPGRADE_FROM|CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_LIC_RELEASE_ID,CAT_SW_LIC_UPGRADE_FROM_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,REQ_SPECIFIC_VERSION,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_PRICING|AVG_PRICE,CAT_CURRENCY_ID,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRICING_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_TAXONOMY2012_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,MAX_PRICE,MIN_PRICE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_REL_LIFECYCLE|CAT_SW_REL_LIFECYCLE_ID,CAT_SW_RELEASE_ID,CREATE_DATE,DELETE_REASON,END_OF_LIFE,END_OF_LIFE_EXCEPTION,END_OF_LIFE_RANGE_END,END_OF_LIFE_RANGE_START,END_OF_LIFE_STR,END_OF_LIFE_SUPPORT_LEVEL,GA_EXCEPTION,GA_RANGE_END,GA_RANGE_START,GENERAL_AVAILABILITY,GENERAL_AVAILABILITY_STR,LAST_MODIFIED_DATE,OBSOLETE,OBSOLETE_EXCEPTION,OBSOLETE_RANGE_END,OBSOLETE_RANGE_START,OBSOLETE_STR,OBSOLETE_SUPPORT_LEVEL,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_SW_REL_SUPP_STAGE|CAT_SUPPORT_STAGE_ID,CAT_SW_REL_SUPP_STAGE_ID,CAT_SW_RELEASE_ID,CREATE_DATE,DATE_ENDDATE,DELETE_REASON,ID,LAST_MODIFIED_DATE,PUBLISHED_ENDDATE,REL_SUPP_STAGE,RELEASE_ID,REPLACEMENT_ID,STAGE_NAME,STAGEORDER,SUPPORT_STAGE_ID,TO_BE_DELETED,TO_BE_DELETED_ON;CAT_WINDOWS7_COMPATIBILITY|CAT_COMPATIBILITY_ID,CAT_COMPATIBILITY_TYPE,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_WINDOWS7_COMPATIBILITY_ID,COMPONENT,CREATE_DATE,DELETE_REASON,EDITION,FAMILY,LAST_MODIFIED_DATE,MANUFACTURER,PATCHLEVEL,REPLACEMENT_ID,SOFTWARE,SUBVERSION,TO_BE_DELETED,TO_BE_DELETED_ON,VERSION,VERSION_GROUP,WIN7_32BIT_COMPAT_DATE,WIN7_32BIT_COMPAT_STATUS,WIN7_32BIT_COMPAT_STATUS_DESC,WIN7_32BIT_COMPAT_UPGRADE_PATH,WIN7_64BIT_COMPAT_DATE,WIN7_64BIT_COMPAT_STATUS,WIN7_64BIT_COMPAT_STATUS_DESC,WIN7_64BIT_COMPAT_UPGRADE_PATH;CAT_WINDOWS8_COMPATIBILITY|CAT_COMPATIBILITY_ID,CAT_COMPATIBILITY_TYPE,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_WINDOWS8_COMPATIBILITY_ID,COMMUNITY_COMPATIBLE,COMMUNITY_NOT_COMPATIBLE,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON,WIN8_32BIT_COMPAT_DATE,WIN8_32BIT_COMPAT_STATUS,WIN8_32BIT_COMPAT_STATUS_DESC,WIN8_32BIT_COMPAT_UPGRADE_PATH,WIN8_64BIT_COMPAT_DATE,WIN8_64BIT_COMPAT_STATUS,WIN8_64BIT_COMPAT_STATUS_DESC,WIN8_64BIT_COMPAT_UPGRADE_PATH;CAT_WINSERVER_COMPATIBILITY|BIT32_COMPAT_STATUS,BIT32_COMPAT_STATUS_DESC,BIT64_COMPAT_STATUS,BIT64_COMPAT_STATUS_DESC,CAT_COMPATIBILITY_ID,CAT_COMPATIBILITY_TYPE,CAT_MANUFACTURER_ID,CAT_SW_EDITION_ID,CAT_SW_PRODUCT_ID,CAT_SW_RELEASE_ID,CAT_SW_VERSION_GROUP_ID,CAT_SW_VERSION_ID,CAT_WINSERVER_COMPATIBILITY_ID,CREATE_DATE,DELETE_REASON,LAST_MODIFIED_DATE,REFERENCE,REPLACEMENT_ID,TO_BE_DELETED,TO_BE_DELETED_ON;";
      //bool a = s.Equals(b);
      //Console.WriteLine(a);
      //=======================================

      //List<TabCol> l = new List<TabCol>();
      //l.Add(new TabCol { TableName = "AA", ColumnName = "ZZ" });
      //l.Add(new TabCol { TableName = "BB", ColumnName = "YY" });
      //l.Add(new TabCol { TableName = "AB", ColumnName = "ZA" });
      //l.Add(new TabCol { TableName = "AD", ColumnName = "ZB" });
      //l.Add(new TabCol { TableName = "AA", ColumnName = "ZA" });
      //l.Add(new TabCol { TableName = "AA", ColumnName = "ZB" });
      //l.Add(new TabCol { TableName = "AA", ColumnName = "ZB" });
      //foreach (TabCol tc in l) Console.WriteLine(tc.TableName + ", " + tc.ColumnName);
      //l = l.OrderBy(x => x.TableName).ThenBy(x => x.ColumnName).ToList();
      //Console.WriteLine("===========after sort==========");
      //foreach (TabCol tc in l) Console.WriteLine(tc.TableName + ", " + tc.ColumnName);
      //=======================================

      //Random r = new Random();
      //for (int i = 0; i < 21; i++)
      //{
      //  int rnum = r.Next(1, 21);
      //  Console.WriteLine(rnum);
      //}
      //=======================================

      //TestStatic.TestStr = "a";
      //Console.WriteLine(TestStatic.TestStr);
      //TestStatic.TestStr = "b";
      //Console.WriteLine(TestStatic.TestStr);
      //=======================================

      //string cellValue = ".5124";
      //Console.WriteLine(Convert.ToDecimal(cellValue, System.Globalization.CultureInfo.CreateSpecificCulture("en-US")));
      //=======================================

      //System.Text.RegularExpressions.Regex reg = new System.Text.RegularExpressions.Regex(@"(?<=[(（])[^（）()]*(?=[)）])");
      //System.Text.RegularExpressions.Match m = reg.Match("NVARCHAR(500)");
      //int len = 1024;
      //if (m.Success)
      //{
      //  Int32.TryParse(m.Value, out len);
      //  Console.WriteLine(m.Value);
      //  Console.WriteLine(len);
      //}
      //=======================================

      //string cellValue = "SWSW_+DM8458+SP10179384+VG42940073";
      //Console.WriteLine(cellValue.TrimEnd());
      //Console.WriteLine(cellValue.Length);
      //Console.WriteLine(Convert.ToString(cellValue));
      //=======================================

      //string p = System.IO.Path.GetFullPath(Environment.ExpandEnvironmentVariables(@"%BMS_HOME%\Abc\abc.txt"));
      //string p = System.IO.Path.GetFullPath(Environment.ExpandEnvironmentVariables(@"d:\a\b\c.txt"));
      //Console.WriteLine(p);
      //=======================================

      //string parent = Directory.GetParent(Path.GetDirectoryName(AppDomain.CurrentDomain.BaseDirectory)).FullName;
      //Console.WriteLine(parent);
      //=======================================

      //testprams("d");
      //=======================================

      //string s = @"Error : The process cannot access the file 'C:\BDNA\Data Platform\bin\bms.Common.dll' because it is being used by another process.";
      //Console.WriteLine(s.IndexOf("Error"));
      //Console.WriteLine(s.Substring(s.IndexOf("Error")));
      //=======================================

      //Console.WriteLine(Path.GetDirectoryName(@"c:\a\c\b.txt"));
      //=======================================

      //List<int> testlist = new List<int>();
      //Stopwatch sw = new Stopwatch();
      //sw.Start();
      //for (int i = 0; i < 10000000; i++)
      //{
      //  testlist.Add(i);
      //}
      //sw.Stop();
      //Console.WriteLine(sw.ElapsedMilliseconds);
      //=======================================

      //object o = true;
      //if (o is string) Console.WriteLine("is bool");

      //bool b = (bool)Convert.ChangeType(0, typeof(bool));
      //Console.WriteLine(b.ToString());

      //string s = (string)Convert.ChangeType("ABC", typeof(string));
      //Console.WriteLine(s);

      //int i = (int)Convert.ChangeType("", typeof(int));   //会出错
      //Console.WriteLine(i);

      //string ss = "";
      //if (ss is string) Console.WriteLine("is string");

      //bool b1 = false;
      //object obj1 = true;
      //if (obj1 is bool) b1 = (bool)obj1;
      //Console.WriteLine(b1.ToString());
      //=======================================

      //string[] ss = { "A", "B", "C" };
      //string s = string.Format("{0} says: {1} and {0} are good friend.", ss);
      //Console.WriteLine(s);
      //=======================================

      bool? b = null;
      Console.WriteLine(b);

    }

    private static void test(SearchOption searchoption)
    {
      searchoption = SearchOption.TopDirectoryOnly;
      Console.WriteLine(searchoption);
    }

    private static void testprams(string pwd)
    {
      pwd = pwd + "abc";
      Console.WriteLine(pwd);
    }

    /// <summary>
    /// 
    /// </summary>
    internal class EnDirectory
    {

      /// <summary>
      /// Gets or sets the full name.
      /// </summary>
      /// <value>
      /// The full name.
      /// </value>
      public string FullName { get; set; }
      public string Name { get; set; }
    }

    internal class EnDirectoryEquality : IEqualityComparer<EnDirectory>
    {

      /// <summary>
      /// Determines whether the specified objects are equal.
      /// </summary>
      /// <param name="x">The first object of type <paramref name="T" /> to compare.</param>
      /// <param name="y">The second object of type <paramref name="T" /> to compare.</param>
      /// <returns>
      /// true if the specified objects are equal; otherwise, false.
      /// </returns>
      public bool Equals(EnDirectory x, EnDirectory y)
      {
        return x.FullName == y.FullName;
      }

      public int GetHashCode(EnDirectory obj)
      {
        if (obj == null)
        {
          return 0;
        }
        else
        {
          return obj.ToString().GetHashCode();
        }
      }
    }

    internal class DirectoryInfoEquality : IEqualityComparer<DirectoryInfo>
    {
      public bool Equals(DirectoryInfo x, DirectoryInfo y)
      {
        return x.FullName == y.FullName;
      }

      public int GetHashCode(DirectoryInfo obj)
      {
        if (obj == null)
        {
          return 0;
        }
        else
        {
          return obj.ToString().GetHashCode();
        }
      }
    }

    internal class Comp : Comparer<string>
    {
      public override int Compare(string x, string y)
      {
        Console.WriteLine("x: {0}", x);
        Console.WriteLine("y: {0}", y);

        if (x == "NBIDLL")
          return -1;
        else
          return 1;
      }
    }

    internal class TabCol
    {
      public string TableName { get; set; }
      public string ColumnName { get; set; }
    }

    internal class TestStatic
    {
      public static string TestStr { get; set; }
    }
  }
}
