//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 
namespace DBHelper.DAO.DAOModel 
{
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class SQLSatement {
        
        private string sqlField;
        
        private int operatetypeField;
        
        private int paramtypeField;
        
        private SQLSatementSqlparame[] sqlparamesField;
        
        private SQLSatementFormatinfo[] formatdetailsField;
        
        /// <remarks/>
        public string sql {
            get {
                return this.sqlField;
            }
            set {
                this.sqlField = value;
            }
        }
        
        /// <remarks/>
        public int operatetype {
            get {
                return this.operatetypeField;
            }
            set {
                this.operatetypeField = value;
            }
        }
        
        /// <remarks/>
        public int paramtype {
            get {
                return this.paramtypeField;
            }
            set {
                this.paramtypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("sqlparame", IsNullable=false)]
        public SQLSatementSqlparame[] sqlparames {
            get {
                return this.sqlparamesField;
            }
            set {
                this.sqlparamesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("formatinfo", IsNullable=false)]
        public SQLSatementFormatinfo[] formatdetails {
            get {
                return this.formatdetailsField;
            }
            set {
                this.formatdetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SQLSatementSqlparame {
        
        private string nameField;
        
        private string dbtypeField;
        
        private string paramevalueField;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string dbtype {
            get {
                return this.dbtypeField;
            }
            set {
                this.dbtypeField = value;
            }
        }
        
        /// <remarks/>
        public string paramevalue {
            get {
                return this.paramevalueField;
            }
            set {
                this.paramevalueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class SQLSatementFormatinfo {
        
        private byte keyField;
        
        private string descField;
        
        private string mockdataField;
        
        private string realdataField;
        
        /// <remarks/>
        public byte key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public string desc {
            get {
                return this.descField;
            }
            set {
                this.descField = value;
            }
        }
        
        /// <remarks/>
        public string mockdata {
            get {
                return this.mockdataField;
            }
            set {
                this.mockdataField = value;
            }
        }
        
        /// <remarks/>
        public string realdata {
            get {
                return this.realdataField;
            }
            set {
                this.realdataField = value;
            }
        }
    }
}
