# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 8086
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: mysql
    hikari:
      connection-timeout: 60000
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: cn.boot.springbootdemo.**
logging:
  level:
    root: info